### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by vigneshvikki** [dhosoft/DhoBlog#205]
i can't install your script

**Comment by vigneshvikki** [comment]
its redirect to localhost/install instead of localhost/dhoblog/install because i am using subdirectory

**Comment by ridho1991** [comment]
this script only works on domain or sub domain.

**Comment by ridho1991** [comment]
you can try use wampp developer (apache) or wtserver (nginx) in windows

**Comment by vigneshvikki** [comment]
i am using wampp but i cant install that script

**Comment by vigneshvikki** [comment]
my base url is $config['base_url'] = 'http://'.$_SERVER['HTTP_HOST'].'/dhoblog';
and this is rewrite module
<IfModule mod_rewrite.c>
RewriteEngine On
    RewriteBase /DhoBlog/
 
    RewriteCond %{REQUEST_URI} ^system.*
    RewriteRule ^(.*)$ /index.php?/$1 [L]
   
    RewriteCond %{REQUEST_URI} ^application.*
    RewriteRule ^(.*)$ /index.php?/$1 [L]
 
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php?/$1 [L]


</IfModule>

**Comment by ridho1991** [comment]
this script only works on domain or sub domain.
you should remove /dhoblog in 'base_url'.
with wampp you can use domain like yourblog.local
since this is under active development, I don't guarantee it will work well, and may contains a lot of bugs.
